# Generated by Django 5.0.4 on 2024-04-18 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='bot',
            field=models.ImageField(default='support.png', upload_to='notifications/images'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='name',
            field=models.CharField(default='Nitro Jemson', max_length=100),
        ),
    ]
