# Generated by Django 5.0.4 on 2024-04-22 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_notification_bot_alter_notification_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exams',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='notification',
            name='bot',
            field=models.ImageField(default='static/support.png', upload_to='notifications/images'),
        ),
    ]
