# Generated by Django 5.0.4 on 2024-04-22 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_exams_alter_notification_bot'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Exams',
            new_name='Exam',
        ),
    ]
