# Generated by Django 5.0.4 on 2024-04-22 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_rename_exams_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='category',
            field=models.CharField(default='', max_length=30),
        ),
    ]
