# Generated by Django 5.0.4 on 2024-04-29 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0005_notification_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scrolling_notifications',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(max_length=80)),
            ],
        ),
    ]
